import type { Metadata } from 'next';
import Image from 'next/image';
import { PageIntro } from '@/components/page-intro';
import { Video } from '@/components/video';
import { Reveal } from '@/components/reveal';
import { StoryProgress } from '@/components/story-progress';
import { stories } from '@/content/stories';
export const metadata:Metadata={title:'Ертегілер әлемі'};

export default function Stories(){return <><PageIntro eyebrow="01 / ТЫҢДА. ҚИЯЛДА. ТАНЫ." title="Ертегілер" accent="әлемі" description="Халық даналығын сақтаған оқиғаларға саяхат. Тыңда, тамашала, өз кейіпкеріңді елестет."/><section className="shell section section-compact"><div className="section-heading"><div><p className="eyebrow">ПРЕЗЕНТАЦИЯДАН · 5–6 СЕКУНДТЫҚ ҮЗІНДІЛЕР</p><h2>Ертегіні <span className="serif">тамашалайық</span></h2></div><span className="count-label">2 қысқа видео</span></div><div className="video-grid">{[{title:'Алтын сақа',src:'media1.mp4',poster:'image6.png',text:'Төзімділік, сақтық және тапқырлық туралы. Видеодан кейін бала кейіпкерінің бейнесін салып көр.'},{title:'Ер Төстік',src:'media2.mp4',poster:'image8.png',text:'Ерлік пен достық туралы. Ер Төстік пен тұлпарын бейнелеп, өзің елестеткен оқиғаны әңгімеле.'}].map(v=><Reveal key={v.src} className="video-card"><Video src={`/media/${v.src}`} poster={`/media/${v.poster}`} title={v.title}/><div className="video-info"><p className="eyebrow">ҚАЗАҚ ХАЛЫҚ ЕРТЕГІСІ</p><h3>{v.title}</h3><p>{v.text}</p></div></Reveal>)}</div></section><section className="tinted-section"><div className="shell section"><div className="section-heading"><div><p className="eyebrow">ОҚУҒА ҰСЫНАМЫЗ · ERTEGILER.KZ</p><h2>Әр ертегі — <span className="serif">бір өнеге</span></h2></div><p>Қысқаша таныс та, толық нұсқасын<br/>түпнұсқа сайттан оқы.</p></div><div className="stories-grid">{stories.map(s=><Reveal className="story-card" id={`story-${s.slug}`} key={s.slug}><div className="story-image"><Image src={s.image} alt={`${s.title} ертегісінің иллюстрациясы`} fill sizes="(max-width: 760px) 90vw, (max-width: 1100px) 50vw, 33vw"/><span className="story-tag">{s.tag}</span></div><div className="story-body"><h3>{s.title}</h3><p>{s.text}</p><StoryProgress slug={s.slug}/></div></Reveal>)}</div><p className="source-note">Ертегілердің толық мәтіні: <a href="https://ertegiler.kz/" target="_blank" rel="noopener noreferrer">Ertegiler.kz</a>. Карточкадағы жаңа иллюстрациялар осы жоба үшін жасалды; Ер Төстік суреті презентациядан алынды.</p></div></section></>}
